[package]
name = "fdate"
version = "1.0.0"
edition = "2018"

license = "Unlicense"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# time in rust sucks??? gonna use chrono
chrono = "0.4"
